# -*- coding: utf-8 -*-

# MultiMessageUI implementation generated from reading ui file 'AudioChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class AudioUI(object):
    def setupUi(self, AudioUI):
        AudioUI.setObjectName("AudioUI")
        AudioUI.resize(396, 321)
        self.centralwidget = QtWidgets.QWidget(AudioUI)
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_3.setGeometry(QtCore.QRect(150, 210, 91, 41))
        self.videoButton_3.setObjectName("videoButton_3")
        self.toSend = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.toSend.setGeometry(QtCore.QRect(40, 30, 311, 151))
        self.toSend.setObjectName("toSend")
        AudioUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AudioUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 22))
        self.menubar.setObjectName("menubar")
        AudioUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AudioUI)
        self.statusbar.setObjectName("statusbar")
        AudioUI.setStatusBar(self.statusbar)

        self.retranslateUi(AudioUI)
        QtCore.QMetaObject.connectSlotsByName(AudioUI)

    def retranslateUi(self, AudioUI):
        _translate = QtCore.QCoreApplication.translate
        AudioUI.setWindowTitle(_translate("AudioChat", "MainWindow"))
        self.videoButton_3.setText(_translate("AudioChat", "挂断"))
        self.toSend.setPlainText(_translate("AudioChat", "您已成功进入语音通话"))
