# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AudioChat.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AudioChat(object):
    def setupUi(self, AudioChat):
        AudioChat.setObjectName("AudioChat")
        AudioChat.resize(396, 321)
        self.centralwidget = QtWidgets.QWidget(AudioChat)
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_2.setGeometry(QtCore.QRect(40, 200, 91, 41))
        self.videoButton_2.setObjectName("videoButton_2")
        self.videoButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_3.setGeometry(QtCore.QRect(260, 200, 91, 41))
        self.videoButton_3.setObjectName("videoButton_3")
        self.toSend = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.toSend.setGeometry(QtCore.QRect(40, 30, 311, 151))
        self.toSend.setObjectName("toSend")
        AudioChat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AudioChat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 396, 22))
        self.menubar.setObjectName("menubar")
        AudioChat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AudioChat)
        self.statusbar.setObjectName("statusbar")
        AudioChat.setStatusBar(self.statusbar)

        self.retranslateUi(AudioChat)
        QtCore.QMetaObject.connectSlotsByName(AudioChat)

    def retranslateUi(self, AudioChat):
        _translate = QtCore.QCoreApplication.translate
        AudioChat.setWindowTitle(_translate("AudioChat", "MainWindow"))
        self.videoButton_2.setText(_translate("AudioChat", "点击发言"))
        self.videoButton_3.setText(_translate("AudioChat", "结束发言"))
        self.toSend.setPlainText(_translate("AudioChat", "当前发言人为："))
