# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class FileUI(object):
    def setupUi(self, FileUI):
        FileUI.setObjectName("FileUI")
        FileUI.resize(497, 400)
        self.centralwidget = QtWidgets.QWidget(FileUI)
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_2.setGeometry(QtCore.QRect(40, 280, 121, 41))
        self.videoButton_2.setObjectName("videoButton_2")
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 10, 381, 241))
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.videoButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_3.setGeometry(QtCore.QRect(180, 280, 121, 41))
        self.videoButton_3.setObjectName("videoButton_3")
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.videoButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_4.setGeometry(QtCore.QRect(320, 280, 121, 41))
        self.videoButton_4.setObjectName("videoButton_4")
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        FileUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FileUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 22))
        self.menubar.setObjectName("menubar")
        FileUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FileUI)
        self.statusbar.setObjectName("statusbar")
        FileUI.setStatusBar(self.statusbar)

        self.retranslateUi(FileUI)
        QtCore.QMetaObject.connectSlotsByName(FileUI)

    def retranslateUi(self, FileUI):
        _translate = QtCore.QCoreApplication.translate
        FileUI.setWindowTitle(_translate("File", "MainWindow"))
        self.videoButton_2.setText(_translate("File", "选择文件"))
        self.videoButton_3.setText(_translate("File", "发送文件"))
        self.videoButton_4.setText(_translate("File", "选择文件夹"))
