# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'File.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_File(object):
    def setupUi(self, File):
        File.setObjectName("File")
        File.resize(497, 400)
        self.centralwidget = QtWidgets.QWidget(File)
        self.centralwidget.setObjectName("centralwidget")
        self.videoButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.videoButton_2.setGeometry(QtCore.QRect(170, 280, 121, 41))
        self.videoButton_2.setObjectName("videoButton_2")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(40, 10, 381, 241))
        self.textBrowser_2.setObjectName("textBrowser_2")
        File.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(File)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 497, 22))
        self.menubar.setObjectName("menubar")
        File.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(File)
        self.statusbar.setObjectName("statusbar")
        File.setStatusBar(self.statusbar)

        self.retranslateUi(File)
        QtCore.QMetaObject.connectSlotsByName(File)

    def retranslateUi(self, File):
        _translate = QtCore.QCoreApplication.translate
        File.setWindowTitle(_translate("File", "MainWindow"))
        self.videoButton_2.setText(_translate("File", "选择文件并发送"))
