# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LocalChatTools.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LocalChatToolsUI(object):
    def setupUi(self, LocalChatToolsUI):
        LocalChatToolsUI.setObjectName("LocalChatToolsUI")
        LocalChatToolsUI.resize(600, 558)
        self.Button2Mode = QtWidgets.QPushButton(LocalChatToolsUI)
        self.Button2Mode.setGeometry(QtCore.QRect(200, 260, 201, 91))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.Button2Mode.setFont(font)
        self.Button2Mode.setObjectName("Button2Mode")
        self.ButtonMutiMode = QtWidgets.QPushButton(LocalChatToolsUI)
        self.ButtonMutiMode.setGeometry(QtCore.QRect(200, 400, 201, 91))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.ButtonMutiMode.setFont(font)
        self.ButtonMutiMode.setObjectName("ButtonMutiMode")
        self.label = QtWidgets.QLabel(LocalChatToolsUI)
        self.label.setGeometry(QtCore.QRect(180, 140, 234, 57))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(LocalChatToolsUI)
        QtCore.QMetaObject.connectSlotsByName(LocalChatToolsUI)

    def retranslateUi(self, LocalChatToolsUI):
        _translate = QtCore.QCoreApplication.translate
        LocalChatToolsUI.setWindowTitle(_translate("LocalChatToolsUI", "LocalChatTools"))
        self.Button2Mode.setText(_translate("LocalChatToolsUI", "双人通信模式"))
        self.ButtonMutiMode.setText(_translate("LocalChatToolsUI", "多人群聊模式"))
        self.label.setText(_translate("LocalChatToolsUI", "LocalChatTools"))
