# -*- coding: utf-8 -*-

# MultiMessageUI implementation generated from reading ui file 'Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class MessageUI(object):
    def setupUi(self, MessageUI):
        MessageUI.setObjectName("MessageUI")
        MessageUI.resize(400, 317)
        self.textBrowser = QtWidgets.QTextBrowser(MessageUI)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 331, 251))
        self.textBrowser.setObjectName("textBrowser")
        self.toSend = QtWidgets.QPlainTextEdit(MessageUI)
        self.toSend.setGeometry(QtCore.QRect(10, 280, 271, 31))
        self.toSend.setObjectName("toSend")
        self.sendButton = QtWidgets.QPushButton(MessageUI)
        self.sendButton.setGeometry(QtCore.QRect(290, 280, 51, 31))
        self.sendButton.setObjectName("sendButton")
        self.videoButton = QtWidgets.QPushButton(MessageUI)
        self.videoButton.setGeometry(QtCore.QRect(340, 20, 56, 31))
        self.videoButton.setObjectName("videoButton")
        self.audioButton = QtWidgets.QPushButton(MessageUI)
        self.audioButton.setGeometry(QtCore.QRect(340, 100, 56, 31))
        self.audioButton.setObjectName("audioButton")
        self.FileButton = QtWidgets.QPushButton(MessageUI)
        self.FileButton.setGeometry(QtCore.QRect(340, 180, 56, 31))
        self.FileButton.setObjectName("FileButton")

        self.retranslateUi(MessageUI)
        QtCore.QMetaObject.connectSlotsByName(MessageUI)

    def retranslateUi(self, MessageUI):
        _translate = QtCore.QCoreApplication.translate
        MessageUI.setWindowTitle(_translate("MessageUI", "MultiMessageUI"))
        self.sendButton.setText(_translate("MessageUI", "发送"))
        self.videoButton.setText(_translate("MessageUI", "视频通话"))
        self.audioButton.setText(_translate("MessageUI", "音频通话"))
        self.FileButton.setText(_translate("MessageUI", "文件传输"))
