# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Message.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MessageUI(object):
    def setupUi(self, MessageUI):
        MessageUI.setObjectName("MessageUI")
        MessageUI.resize(511, 367)
        self.textBrowser = QtWidgets.QTextBrowser(MessageUI)
        self.textBrowser.setGeometry(QtCore.QRect(10, 20, 331, 261))
        self.textBrowser.setObjectName("textBrowser")
        self.toSend = QtWidgets.QPlainTextEdit(MessageUI)
        self.toSend.setGeometry(QtCore.QRect(10, 300, 331, 51))
        self.toSend.setObjectName("toSend")
        self.sendButton = QtWidgets.QPushButton(MessageUI)
        self.sendButton.setGeometry(QtCore.QRect(350, 300, 131, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.sendButton.setFont(font)
        self.sendButton.setObjectName("sendButton")
        self.videoButton = QtWidgets.QPushButton(MessageUI)
        self.videoButton.setGeometry(QtCore.QRect(350, 20, 131, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.videoButton.setFont(font)
        self.videoButton.setObjectName("videoButton")
        self.audioButton = QtWidgets.QPushButton(MessageUI)
        self.audioButton.setGeometry(QtCore.QRect(350, 90, 131, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.audioButton.setFont(font)
        self.audioButton.setObjectName("audioButton")
        self.FileButton = QtWidgets.QPushButton(MessageUI)
        self.FileButton.setGeometry(QtCore.QRect(350, 160, 131, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.FileButton.setFont(font)
        self.FileButton.setObjectName("FileButton")
        self.backButton = QtWidgets.QPushButton(MessageUI)
        self.backButton.setGeometry(QtCore.QRect(350, 230, 131, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.backButton.setFont(font)
        self.backButton.setObjectName("backButton")

        self.retranslateUi(MessageUI)
        QtCore.QMetaObject.connectSlotsByName(MessageUI)

    def retranslateUi(self, MessageUI):
        _translate = QtCore.QCoreApplication.translate
        MessageUI.setWindowTitle(_translate("MessageUI", "MessageUI"))
        self.sendButton.setText(_translate("MessageUI", "发送"))
        self.videoButton.setText(_translate("MessageUI", "视频通话"))
        self.audioButton.setText(_translate("MessageUI", "音频通话"))
        self.FileButton.setText(_translate("MessageUI", "文件传输"))
        self.backButton.setText(_translate("MessageUI", "返回"))
