# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MultiHost.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MultiHostUI(object):
    def setupUi(self, MultiHostUI):
        MultiHostUI.setObjectName("MultiHostUI")
        MultiHostUI.resize(509, 423)
        self.label = QtWidgets.QLabel(MultiHostUI)
        self.label.setGeometry(QtCore.QRect(150, 30, 191, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(MultiHostUI)
        self.lineEdit.setGeometry(QtCore.QRect(130, 60, 231, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(MultiHostUI)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 251, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(MultiHostUI)
        self.lineEdit_2.setGeometry(QtCore.QRect(130, 160, 231, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(MultiHostUI)
        self.pushButton.setGeometry(QtCore.QRect(340, 320, 91, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(MultiHostUI)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_3 = QtWidgets.QLabel(MultiHostUI)
        self.label_3.setGeometry(QtCore.QRect(180, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(MultiHostUI)
        self.lineEdit_3.setGeometry(QtCore.QRect(130, 270, 231, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(MultiHostUI)
        QtCore.QMetaObject.connectSlotsByName(MultiHostUI)

    def retranslateUi(self, MultiHostUI):
        _translate = QtCore.QCoreApplication.translate
        MultiHostUI.setWindowTitle(_translate("MultiHostUI", "MultiHost"))
        self.label.setText(_translate("MultiHostUI", "你当前本机的IP是"))
        self.label_2.setText(_translate("MultiHostUI", "你想开放的本机端口为"))
        self.pushButton.setText(_translate("MultiHostUI", "确定开启"))
        self.pushButton_2.setText(_translate("MultiHostUI", "返回"))
        self.label_3.setText(_translate("MultiHostUI", "你的昵称为"))
