# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MultiClient.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MultiClientUI(object):
    def setupUi(self, MultiClientUI):
        MultiClientUI.setObjectName("MultiClientUI")
        MultiClientUI.resize(430, 451)
        self.label = QtWidgets.QLabel(MultiClientUI)
        self.label.setGeometry(QtCore.QRect(120, 30, 191, 21))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(MultiClientUI)
        self.lineEdit.setGeometry(QtCore.QRect(100, 60, 231, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(MultiClientUI)
        self.label_2.setGeometry(QtCore.QRect(120, 130, 251, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(MultiClientUI)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 180, 231, 41))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(MultiClientUI)
        self.pushButton_2.setGeometry(QtCore.QRect(60, 360, 91, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton = QtWidgets.QPushButton(MultiClientUI)
        self.pushButton.setGeometry(QtCore.QRect(300, 360, 91, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(MultiClientUI)
        self.label_3.setGeometry(QtCore.QRect(160, 240, 251, 41))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(MultiClientUI)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 290, 231, 41))
        self.lineEdit_3.setObjectName("lineEdit_3")

        self.retranslateUi(MultiClientUI)
        QtCore.QMetaObject.connectSlotsByName(MultiClientUI)

    def retranslateUi(self, MultiClientUI):
        _translate = QtCore.QCoreApplication.translate
        MultiClientUI.setWindowTitle(_translate("MultiClientUI", "MultiClient"))
        self.label.setText(_translate("MultiClientUI", "你需要连接的IP是"))
        self.label_2.setText(_translate("MultiClientUI", "你想连接的端口为"))
        self.pushButton_2.setText(_translate("MultiClientUI", "返回"))
        self.pushButton.setText(_translate("MultiClientUI", "确定"))
        self.label_3.setText(_translate("MultiClientUI", "你的昵称为"))
