# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TwoConnect.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class TwoConnectUI(object):
    def setupUi(self, TwoConnectUI):
        TwoConnectUI.setObjectName("TwoConnectUI")
        TwoConnectUI.resize(400, 300)
        self.currentIP = QtWidgets.QTextBrowser(TwoConnectUI)
        self.currentIP.setGeometry(QtCore.QRect(30, 30, 351, 31))
        self.currentIP.setObjectName("currentIP")
        self.label = QtWidgets.QLabel(TwoConnectUI)
        self.label.setGeometry(QtCore.QRect(30, 110, 141, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(TwoConnectUI)
        self.label_2.setGeometry(QtCore.QRect(30, 150, 141, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(TwoConnectUI)
        self.label_3.setGeometry(QtCore.QRect(30, 190, 161, 31))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(TwoConnectUI)
        self.pushButton.setGeometry(QtCore.QRect(260, 250, 93, 28))
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoExclusive(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(TwoConnectUI)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 250, 93, 28))
        self.pushButton_2.setCheckable(False)
        self.pushButton_2.setAutoRepeat(False)
        self.pushButton_2.setAutoExclusive(False)
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setDefault(False)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.portToConnect = QtWidgets.QPlainTextEdit(TwoConnectUI)
        self.portToConnect.setGeometry(QtCore.QRect(210, 110, 171, 31))
        self.portToConnect.setObjectName("portToConnect")
        self.ipToConnect = QtWidgets.QPlainTextEdit(TwoConnectUI)
        self.ipToConnect.setGeometry(QtCore.QRect(210, 150, 171, 31))
        self.ipToConnect.setObjectName("ipToConnect")
        self.openPort = QtWidgets.QPlainTextEdit(TwoConnectUI)
        self.openPort.setGeometry(QtCore.QRect(210, 190, 171, 31))
        self.openPort.setObjectName("openPort")
        self.label_5 = QtWidgets.QLabel(TwoConnectUI)
        self.label_5.setGeometry(QtCore.QRect(30, 70, 141, 31))
        self.label_5.setObjectName("label_5")
        self.nickNameInput = QtWidgets.QPlainTextEdit(TwoConnectUI)
        self.nickNameInput.setGeometry(QtCore.QRect(210, 70, 171, 31))
        self.nickNameInput.setObjectName("nickNameInput")
        self.label_4 = QtWidgets.QLabel(TwoConnectUI)
        self.label_4.setGeometry(QtCore.QRect(150, 230, 161, 31))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(TwoConnectUI)
        QtCore.QMetaObject.connectSlotsByName(TwoConnectUI)

    def retranslateUi(self, TwoConnectUI):
        _translate = QtCore.QCoreApplication.translate
        TwoConnectUI.setWindowTitle(_translate("TwoConnectUI", "Form"))
        self.currentIP.setHtml(_translate("TwoConnectUI",
                                          "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                                          "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                                          "p, li { white-space: pre-wrap; }\n"
                                          "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                                          "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">你的当前IP是:</p></body></html>"))
        self.label.setText(_translate("TwoConnectUI", "你想要连接的端口是："))
        self.label_2.setText(_translate("TwoConnectUI", "你想要连接的IP是："))
        self.label_3.setText(_translate("TwoConnectUI", "你想要开放连接端口是："))
        self.pushButton.setText(_translate("TwoConnectUI", "确定连接"))
        self.pushButton_2.setText(_translate("TwoConnectUI", "返回"))
        self.label_5.setText(_translate("TwoConnectUI", "你的昵称是："))
        self.label_4.setText(_translate("TwoConnectUI", "正在连接中..."))
